### ISSUE TITLE
Error 259 when sending mp3 file

### ISSUE THREAD

**Issue by Neo-Turak** [jimlawless/cmdmp3#2]
Error 263 when sending Player theMP3 Wait

**Comment by jimlawless** [comment]
I believe that this is because the volume that your MP3 file is on does not permit shortened names.  I'll make a change to enclose the filename in single-quotes instead of shortening the name.

**Comment by jimlawless** [comment]
I have rebuilt the code, but I'm no longer able to play MP3's with this program on my own Windows box due to Windows playing them natively instead of using the codecs ( or so I've read. )  However, I did make the change in the code that shortens the filename.  Would you please test the version(s) at http://www.mailsend-online.com/wp/cmdmp3alt.zip and let me know if this fixes your issue?

If so, I'll update the sources here.

**Comment by gugglegum** [comment]
I have similar error, but code little different. The same in both 2.0 and 2.1 versions ("new" and "alt"). I used simple sound sample recorded in wav and mp3. And always getting this:
```
D:\Users\Pavel\Downloads\cmdmp3alt>cmdmp3.exe test.mp3
cmdmp3 v2.1
Command-line MP3 player
by Jim Lawless - http://jiml.us

Error 275 when sending Open 'test.mp3' Type MPEGVideo Alias theMP3
Error 263 when sending Play theMP3 Wait
```
Little different error code (277 instead of 275) when opening general mp3 file with long file name:
```
D:\Users\Pavel\Downloads\cmdmp3alt>cmdmp3.exe D:\Users\Pavel\Music\BlackeyedPeas-IGottaFeeling.mp3
cmdmp3 v2.1
Command-line MP3 player
by Jim Lawless - http://jiml.us

Error 277 when sending Open 'D:\Users\Pavel\Music\BlackeyedPeas-IGottaFeeling.mp3' Type MPEGVideo Alias theMP3
Error 263 when sending Play theMP3 Wait

D:\Users\Pavel\Downloads\cmdmp3new>cmdmp3.exe D:\Users\Pavel\Music\BlackeyedPeas-IGottaFeeling.mp3
cmdmp3 v2.0
Command-line MP3 player
by Jim Lawless - http://jiml.us

Error 277 when sending Open D:\Users\Pavel\Music\BLACKE~1.MP3 Type MPEGVideo Alias theMP3
Error 263 when sending Play theMP3 Wait
```
I have Windows 7 Pro x64 SP1.

**Comment by jimlawless** [comment]
> Error 277 when sending Open D:\Users\Pavel\Music\BLACKE~1.MP3 Type MPEGVideo Alias theMP3
> Error 263 when sending Play theMP3 Wait

Please take a look at the comments to this post:

https://lawlessguy.wordpress.com/2015/06/27/update-to-a-command-line-mp3-player-for-windows/

I'm afraid that Windows began to process MP3's directly instead of letting the multimedia interface handle them.  There are some links in the conversation about some folks who've had some luck by installing codecs, but it doesn't always seem to work.  I have this same problem on my Windows 10 machines.  ( I should change the error messages to indicate this. )

The player has never played WAV files.  I'm sure there are command-line WAV players out there.  If not, I'll code one up.
